# -*- coding: utf-8 -*-
"""lab1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q9QAJxLFOyYXTAQWesxLi7Jb7-eUWbeb
"""

import pandas as pd

df = pd.read_csv("restaurant_info(1).csv")

pref_dict = {"area":'centre',"pricerange":'expensive',"food":'british'}

def lookup(dictionary):
  string = "ilevel_0 in ilevel_0"
  for i in dictionary:
    if dictionary[i] != "dontcare":
      string += " and " + str(i) + " == '" + str(dictionary[i]) + "'"
  df2 = df.query(string)
  rest_list = [i for i in df2['restaurantname']]
  return (rest_list)

lookup(pref_dict)
